format = "$directory λ "

[directory]
format = "[$path](green)[$read_only](red)"
read_only = " "
truncate_to_repo = true
truncation_length = 1

[time]
disabled = true

[hostname]
disabled = true

[battery]
disabled = true
