format = "$directory "
add_newline = true


[directory]
format = "[$path](dimmed)[$read_only](red)"
read_only = " "
truncate_to_repo = true
truncation_length = 1

[time]
disabled = true

[hostname]
disabled = true

[battery]
disabled = true
